[package]
name = "create-rust-app"
version = "0.1.0"
authors = ["Haris <4259838+Wulf@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
